### PR TITLE
Achieve high availability of Maxwell

### PR DESCRIPTION
**Pull request by wanghangyu817**
Start ZooKeeper and add --ha_mode=true -- zookeeper_server =' XXX :2181' to maxwell startup script. Perform the same operation on another server or multiple servers to complete maxwell high availability mode. If you want to see who the leader of maxwell is currently running,Executable maxwell-leaders --ha_mode=true -- zookeeper_server =' XXX :2181' get the current Maxwell leaders

### CODE REVIEW

**Comment by wanghangyu817** [comment]
Who can tell me what to do (security/ Snyk (Goanna)）?

**Comment by osheroff** [comment]
thanks for the PR!  I'll find some time to look at this soon.

**Comment by wanghangyu817** [comment]
Hi @osheroff  ，This PR, is there a problem or lack of performance

**Comment by osheroff** [comment]
i DIY'ed this

**Pull request closed without merging**
