### PR TITLE
Redis reconnection handling

### PR DESCRIPTION
**Pull request by lucastex**
Hi @osheroff 

This pull request recreates the Jedis connection when the jedis lost its connection instead of just invoking the `connect()` method. 

I've noticed that after reconnection failed for three times, the messaged failed but it was not incrementing the maxwell's failed messages internal counter. I've moved this outside the loop with a control variable `sentToRedis` and removed the succes incrementing to the same block. What do you think?

If you prefer, I can sent another with only the reconnecting issue.

### CODE REVIEW

**Comment by osheroff** [comment]
looks good to me!  did you test this code?  did it fix the issue?

**Comment by lucastex** [comment]
Thanks @osheroff ! 

Yes, I've tested and it is running great in our DEV / QA and couldn't reproduce the problem. I'll check again in the production environment after the release. 

We've faced this issue only a few few times in DEV / QA, it happens mainly in our prod env.

Thanks a lot for the opportunity on contributing. Waiting for your next steps.

**Comment by osheroff** [comment]
next steps, I'm merging.  thanks for the work!  I'll get a release out tomorrow-ish, I don't think there's anything else in the pipeline but I can easily do a patch release for this one.

**Comment by lucastex** [comment]
Thanks a lot! As soon you release it, will test it here in production.

**Comment by osheroff** [comment]
released in 1.26.1

**Comment by lucastex** [comment]
That's it @osheroff 

Running in production since yesterday... I can see the errors happening, but right after the error, the connection restabilshes and keep sending to redis.

Thanks a lot for the help!

**Pull request merged**
