### PR TITLE
Alter table cascade

### PR DESCRIPTION
**Pull request by smferguson**
#458 fix - allow 'cascade' keyword in alter table - _Note that this is blocked by #457 because i was lazy with my branching before_ :/

### CODE REVIEW

**Comment by osheroff** [comment]
`git cherry-pick` is your friend here.

**Comment by osheroff** [comment]
also plz accompany fixes like this with a one-line SQL statement in src/test/java/com/zendesk/maxwell/schema/ddl/DDLParserTest.java

**Comment by smferguson** [comment]
ahh yes. i forget cherry picking has good use cases. long ago and architect forced me to cherry pick _everything_ so i'm a bit scarred there. thanks for the reminder.
tbh, i don't know what cascade does here. it's from code generated by another team in django... i hate ORM layers.
will add a test for this to the parser.

**Comment by osheroff** [comment]
build failed, but it looks transient.  The code changes are fine, just need to migrate them to a clean branch and open a different pr....

**Pull request closed without merging**
