### PR TITLE
Support for RabbitMQ as message bus in addition to Kafka

### PR DESCRIPTION
**Pull request by w7089**
It's initial commit for your review. 
General list of changes:
1) Configuration file support
2) Addition of RabbitMQProducer
3) Addition of MessageBusManager for managing connections to RabbitMQ

### CODE REVIEW

**Comment by w7089** [comment]
what's is the reason for failing build? Can't understand the "build failed" message in Travis...

**Comment by aditya-cap** [comment]
I'm interested in this pull request. @w7089 - were you able to resolve the build issues ?

**Comment by timbertson** [comment]
Unfortunately there is another rabbitMQ PR: #525. It looks a bit less invasive and has had more review so we're likely to proceed with that one, but I don't know much rabbitMQ so please get involved if you think there are important differences.

For this PR, it looks like there is a bit of cleanup required (e.g. excess logging, commented out code, odd formatting (lots of blank lines, use of spaces instead of tabs). It'd need a rebase, and you should implement proper termination behaviour (i.e. call context.terminate() on exception, and implement any shutdown steps needed).

**Comment by timbertson** [comment]
Closing in favour of #734

**Pull request closed without merging**
