### PR TITLE
added changes to support separate topic for each database and table 

### PR DESCRIPTION
**Pull request by MaheshMadushnaka**
When we start maxwell if we pass 
1. \-  --kafka_topic='database.table'    create separate topic for each database table
2. \- --kafka_topic='database'             create separate topic for each database

else use default topic

### CODE REVIEW

**Comment by osheroff** [comment]
Hi Mahesh, thanks for the PR.  This is a nice feature, but I'd like it to be more robust.  Specifically:

- it should have its own command-line flag (`--kafka_topic_per_table`, `--kafka_topic_per_db_and_table`)
- It needs to be aware of kafka setups where topics are not auto-created, and do something smart there (either warn once and drop the message, or crash, or have a flag that toggles things, or something)

**Comment by MaheshMadushnaka** [comment]
@osheroff  thanks for your feedback ill add those changes and commit it again.

**Comment by MaheshMadushnaka** [comment]
@osheroff  as you requested added command line flags for db level and table level  topics creation 

you can use following flags to create separate kafka topic for database level and and table level 

-kafka_topic_per_table 
--kafka_topic_per_db

**Comment by MaheshMadushnaka** [comment]
@osheroff  added those command line flags can you please review this and aprove

**Comment by osheroff** [comment]
Hi, 
So this PR has whitespace issues.  Please configure your editor correctly.  

Also, it still needs to do something about a setup where topics are not auto-created.

**Comment by smferguson** [comment]
@MaheshMadushnaka no activity on this for a while. is it still alive? I'm interested in this feature as well.

**Comment by osheroff** [comment]
@smferguson if you've got any time https://github.com/zendesk/maxwell/pull/407 is the closest of the 3 (!) PRs that have attempted this feature.  I was thinking I would just go finish the thing when I got some time, but LMK if you're gonna hit it.

**Comment by smferguson** [comment]
@osheroff 👍  i'm prob a week away from being able to think about it. i'll tag the PR when/if i start.

**Comment by osheroff** [comment]
completed elsewhere

**Pull request closed without merging**
