### PR TITLE
Allow LOCALTIME and LOCALTIMESTAMP as default values

### PR DESCRIPTION
**Pull request by hexene**

### CODE REVIEW

**Comment by hexene** [comment]
`LOCALTIME` and `LOCALTIMESTAMP` are synonyms for `NOW()`: https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_localtime

**Comment by hexene** [comment]
Assuming this change is OK, will add a test once #797 is merged to avoid a merge-conflict.

**Comment by liulikun** [comment]
Yup, looks good!

**Comment by timbertson** [comment]
#797 merged, fire away with tests :)

**Comment by osheroff** [comment]
`mysql_literal_tokens.g4` is a file generated from the ruby script in the directory.  need to edit that file instead.

**Comment by osheroff** [comment]
I added some tests and merged a rebased version of this.

**Pull request closed without merging**
