### PR TITLE
add option to ignore ddl statement parsing

### PR DESCRIPTION
**Pull request by powerLambda**
DDL parsing is mandatory in current code, any parsing error will cause maxwell replicator fatal error and stop execution. 

In most cases, DDL parsing are successful, but some exotic DDL statement does cause parsing issue. maybe in near future mysql will have more minor SQL syntax changes and cause maxwell DDL parsing error.  
Maybe we could add a option to ignore DDL parsing?  

I think it is "safe" option for stable production system(**actually no DDL changes in our production system**) but with multiple tenement. other users's exotic DDL changes may have a impact to maxwell normal execution.

```
3:50:50,710 INFO  AbstractSchemaStore - storing schema @BinlogPosition[mysql-bin.003981:29180028] after applying "DROP TABLE IF EXISTS `xxx_asset_access_audit` /* generated by server */"
23:50:50,777 ERROR MysqlParserListener - (creation_engine ENGINE = `InnoDB`)
23:50:50,777 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE `xxx_asset_access_audit` (
        `id` int(11) NOT NULL,
        `partner_id` varchar(31) NOT NULL ,
        `partner_product_id` varchar(31) NOT NULL ,
        `log_date` datetime NOT NULL ,
        `batch_id` varchar(64) NOT NULL ,
        `order_id` varchar(64) NOT NULL ,
        `audit_status` tinyint(4) NOT NULL ,
        `audit_reason` varchar(255) DEFAULT NULL ,
        `remark` varchar(255) DEFAULT ',
        `is_deleted` char(1) NOT NULL DEFAULT 'N' ,
        `gmt_created` datetime NOT NULL ,
        `creator` varchar(32) NOT NULL ,
        `gmt_modified` datetime NOT NULL ,
        `modifier` varchar(32) NOT NULL ,
        PRIMARY KEY (`id`),
        UNIQUE `UN_ORDER` (`partner_product_id`, `batch_id`, `order_id`) comment ''
) ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT  CHECKSUM=0 DELAY_KEY_WRITE=0'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: `InnoDB`
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:33)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:47)
        at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:344)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:321)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:113)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:32)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)
23:50:50,823 INFO  PositionStoreThread - Storing final position: BinlogPosition[mysql-bin.003981:29179353]
```

### CODE REVIEW

**Comment by osheroff** [comment]
Hi @powerLambda,
No, this is not safe.  Maxwell needs to have an up-to-date copy of the schema in order to function at all.  Please open an issue (or PR?) for your particular parsing problem.

**Comment by powerLambda** [comment]
@osheroff, DDL parsing is the most tricky part for me. In some simple use case, only 4~5 tables(rarely change DDL) are monitored but all DDL changes are required to be parsed(multi-tenant database, more that 100 database).
I know Maxwell needs to have an up-to-date copy of the schema. but for this simple case(small number of tables, rarely DDL change),  I can stop maxwell and re-initialized maxwell schema to get the up-to-date schema if my favorite table DDL changed.(easy operation).
In my test, If I disable DDL parsing feature, the stability increase greatly in multi-tenant environment..

**Comment by powerLambda** [comment]
new issue is created as below:
https://github.com/zendesk/maxwell/issues/418

**Comment by osheroff** [comment]
thx for the issue.  Will fix the parsing error.  I see your use case, and I'm a bit torn.  How about instead of this, a patch that will rescue sql parse errors (and log them, heavily) and re-capture the schema?  This PR just feels like it's a big shotgun waiting for a foot.

**Comment by powerLambda** [comment]
@osheroff  thanks for the quick fix.  One concern about the schema re-capture the  is the replica falls too far behind.  I prefer the "simple and stupid" solution. :)
 
Because I found it is hard to maintain the complete database schema in maxwell when using cloud vendor provided mysql(multi-tenant, 100+ database).   

For exapmle, maxwell often stopped caused by "com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find database 'cmis_haierdb'".
I found 'cmis_haierdb' database/table schema information are unaccessible in INFORMATION_SCHEMA, unless DBA assign 'cmis_haierdb' database access to my replication account.

Irrelevant DDL parsing error and [above missing schema](https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellReplicator.java#L190) will throw run-time exception and often killed maxwell. 

I propose to give user a option to not maintain the complete schema structure, more fault tolerant when [schema missing](https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellReplicator.java#L190) or DDL parsing error.

**Comment by mieciu** [comment]
To be honest, I don't understand, why ``` Maxwell needs to have an up-to-date copy of the schema in order to function at all. ```

Why maxwell has to take care about schema? Taking a step back,  I can imagine that it just forwards information about DDL, DML, queries as unstructured objects (events) to Kafka.

**Comment by osheroff** [comment]
the schema's where the column names are.  also the character set of a string, also the signed-ness of an integer.  Also the names of values in a set/enum.   

You're welcome to unstructured objects, but you don't need maxwell.  just try the output of `mysqlbinlog -vv`

**Comment by osheroff** [comment]
I'm honestly never going to merge this, sorry.

**Pull request closed without merging**
