### PR TITLE
mysql-test, part 5

### PR DESCRIPTION
**Pull request by osheroff**
NO MERGEY MERGE

- bring in `DROP KEY` from another PR
- bring in `STATS_AUTO_RECALC`
- remove a bunch of garbagey test data

@zendesk/rules

### CODE REVIEW

**Comment by lileeyao** [comment]
why are we not using codecov in other repos, this tool looks really decent.

**Comment by vanchi-zendesk** [comment]
:+1: 

How do you plan to maintain this test data? It's unreviewable. Could this be generated on the fly instead?

**Comment by osheroff** [comment]
@vanchi-zendesk, it is generated dynamically.  I have three files:

- mysql-test.sql -- this contains the DDL I captured from a run of mysql-test
- mysql-test-errors.sql -- that which is still in error
- mysql-test-fixed.sql -- that which is fixed.

but generated on the fly from mysql-test?  No.  That script is a huge pain, I had to hack it and munge it to generate the file in the first place, and it still output junk data here & there.

**Comment by osheroff** [comment]
@lileeyao we certainly could use codecov elsewhere.  I'm not totally sure I like how it comments on every PR, but it's not bad.  The only thing is that to do anything with our non-public repos people have to sign things, legal has to get involved; dumb stuff like that.

**Comment by osheroff** [comment]
merged manually.

**Pull request closed without merging**
