### PR TITLE
add back version into into jar

### PR DESCRIPTION
**Pull request by osheroff**
we lost this when switching from Make to maven

### CODE REVIEW

**Comment by ashashwat** [comment]
@osheroff  This did not work for me.  :(

I tried, 
```
% make package 
% bin/maxwell --user='maxwell' --password='maxwell' --host='127.0.0.1' --producer=kafka --kafka.bootstrap.servers=localhost:9092 --kafka_topic=test 
```

This was the result,  

<snip>
00:19:32,381 INFO  AppInfoParser - Kafka version : 0.11.0.1
00:19:32,381 INFO  AppInfoParser - Kafka commitId : c2a0d5f9b1f45bf5
00:19:32,405 INFO  Maxwell - Maxwell v?? is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[1.000006:9400351], lastHeartbeat=1519059423524]

**Comment by ashashwat** [comment]
@osheroff This was my first attempt at fixing this as described in [Issue #889](https://github.com/zendesk/maxwell/issues/889) but for some reason, this did not work for me.

**Comment by osheroff** [comment]
@ashashwat yeah, it won't work in development mode but will work in the generated tarball/jar

**Comment by ashashwat** [comment]
@osheroff  Yeah, worked for me in the generated tarball/jar.

**Pull request merged**
