### PR TITLE
Add --skip_positions option

### PR DESCRIPTION
**Pull request by justinmichaud**
This PR adds a --skip_positions=file1:123-456,file2:111-111 option. The intent behind this option is to allow maxwell to safely skip over a log entry in the event of a bug.

Question for reviewer: Currently, `testThatSkipPositionsDoesNotParseCrashes` does not work as intended. The intent here is to make sure that maxwell does not try to parse the binlog. The test is not strictly necessary, but if you can think of a way to test this, please let me know. I manually tested this by reverting https://github.com/zendesk/maxwell/pull/907/files, to give you an idea of the case that I am worrying about. If there was some way of injecting an invalid binlog into the stream that maxwell reads, that would be great.

Let me know if you want any changes. Thanks!

### CODE REVIEW

**Comment by justinmichaud** [comment]
Hey @osheroff, do you have any ideas for how I can test that this does no parsing?

**Comment by justinmichaud** [comment]
Hey @osheroff, are you still willing to merge this feature?

**Comment by liulikun** [comment]
Feel a bit heavy handed to handle this situation since the config is checked on every single event even it may only happen occasionally. What about manually updating `positions` table on those occasions to skip the position?

**Comment by osheroff** [comment]
sorry for the long delay @justinmichaud I've had this PR in the back of my mind for awhile.  I have a second use for this PR in wall-papering over some race conditions in the `SchemaCapturer`, but I think what I'd like to see is instead of a list of positions to skip, make this instead "ignore-schema-errors-through".  The premise is that you'd pick a target binlog position, and maxwell would ignore any ddl-errors that result until you've processed through that position.  It'd be roughly analogous to the `skip-slave-errors` option in mysql.

This would have the side-benefit of only checking the variable when the ddl throws.

Would that be an ok approach to solving your problem?

**Comment by justinmichaud** [comment]
Hmm, I'm not sure. I was hoping to use this in case of another parsing error, but I suppose those are quite rare so it might be fine.

If we would cache the check that the config option is enabled, would that solve your concerns about performance?

**Comment by osheroff** [comment]
So I have less of a performance concern, I just want to be able to ignore DDL errors between two different positions - in my code I won’t know where the specific error is (if there is any)

**Pull request closed without merging**
