### PR TITLE
(master-recovery, part 2) Add a heartbeat and replica_server_id

### PR DESCRIPTION
**Pull request by osheroff**
This is part 2 of a many part PR series.

The plot thickened a bit with regards to running multiple copies of maxwell, and also with regard to doing master recovery.  

For multiple copies of Maxwell run on 5.5, each must have a unique server_id or mysql will unceremoniously cut the connection.

@zendesk/rules

### CODE REVIEW

**Comment by dadah89** [comment]
lgtm 👍 (I'm assuming you'll start using `heartbeat` in a subsequent PR)

**Comment by osheroff** [comment]
@dadah89 updated to actually send heartbeats

**Comment by dadah89** [comment]
👍

**Comment by osheroff** [comment]
merged by hand

**Pull request closed without merging**
