### PR TITLE
Modified the behaviour of the lifecycle when a communication error arises trying to read binlogs from MySQL.

### PR DESCRIPTION
**Pull request by acampoh**
Now maxwell will be halted in order to avoid looping only throwing errors.

Please, let me know if there is a better way to do this, so i can update my PR

Thanks!

### CODE REVIEW

**Comment by osheroff** [comment]
cool, it's a start!  Try this as an approach instead:

- BinlogConnectorLifecycleListener passes the exception to `BinlogConnectorReplicator` like this:

```
   class BinlogConnectorLifecycleListener implements BinaryLogClient.LifecycleListener {
	public BinlogConnectorLifecyleListener(BinlogConnectorReplicator replicator) {
             this.replicator = replicator;
        }
	@Override
	public void onCommunicationFailure(BinaryLogClient client, Exception ex) {
		this.replicator.setBinlogConnectorException(ex);
	}
```

And then we check for this exception somewhere in the `BinlogConnectorReplicator` run-loop -- `ensureReplicatorThread` feels like a natural place for the check. 

*if* the exception is one of the types of exceptions we'll never recover from via reconnect (we'll need to figure out the server error code of the exception you're seeing), re-throw the exception up the stack.  This should crash maxwell.

Clear?  LMK if you have any questions.

**Comment by osheroff** [comment]
take a look at https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/Maxwell.java#L154 -- all the termination and such is handled outside of the replicator.  So the replicator itself is free to crash via exception, the outer code will handle the clean shutdown.

**Comment by acampoh** [comment]
i see, i'll do it in that way then

**Comment by acampoh** [comment]
just tried that way and as the exception doesn't reach the Maxwell class (it's thrown from the lifecycle listener) and it doesn't stop the process (even with a runtimeException)

i have seen that calling Maxwell terminate from there works fine. (here is the log)

```16:15:49,012 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.network.ServerException: The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:885) [mysql-binlog-connector-java-0.17.0.jar:0.17.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:564) [mysql-binlog-connector-java-0.17.0.jar:0.17.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:796) [mysql-binlog-connector-java-0.17.0.jar:0.17.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
16:15:49,024 INFO  MaxwellContext - Sending final heartbeat: 1547651749024
16:15:54,048 WARN  MaxwellContext - Timed out waiting for heartbeat 1547651749024
16:15:54,054 INFO  TaskManager - Stopping 2 tasks
16:15:54,055 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@3074193c
16:15:54,055 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
16:15:54,055 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@3eb3f142
16:15:54,055 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
Disconnected from the target VM, address: '127.0.0.1:44085', transport: 'socket'
16:15:55,267 ERROR MaxwellContext - Exception occurred during shutdown:
java.util.concurrent.TimeoutException: Timed out trying waiting for com.zendesk.maxwell.replication.BinlogConnectorReplicator process to stop after 1000ms.
	at com.zendesk.maxwell.util.StoppableTaskState.awaitStop(StoppableTaskState.java:46) ~[classes/:?]
	at com.zendesk.maxwell.util.RunLoopProcess.awaitStop(RunLoopProcess.java:18) ~[classes/:?]
	at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:53) ~[classes/:?]
	at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:165) [classes/:?]
	at com.zendesk.maxwell.MaxwellContext.access$000(MaxwellContext.java:32) [classes/:?]
	at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:188) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
16:15:55,269 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process

i'll update the PR with the new changes

**Comment by osheroff** [comment]
> just tried that way and as the exception doesn't reach the Maxwell class (it's thrown from the lifecycle listener) 

Right, don't throw it from the lifecycle listener.  Pass it back to the replicator so it can throw it from somewhere in `work`, like I was suggesting.

**Comment by acampoh** [comment]
done!

Let's see if this time is the good one :)

**Comment by acampoh** [comment]
let's see this time :P

**Comment by osheroff** [comment]
thanks very much!  👍

**Pull request merged**
