### PR TITLE
initial spike checkin for state port

### PR DESCRIPTION
**Pull request by nnordrum**
I'm not intending this to be merged, so don't worry. Just trying to start the conversation about how to make it better.

### CODE REVIEW

**Comment by osheroff** [comment]
running out the door so more later, but avoid a singleton here; there's an effort afoot to make maxwell into a library (interfacing with kafka-connect), and best if all global-ish state gets stashed into `MaxwellContext`

**Comment by smferguson** [comment]
@osheroff what's your opinion here? is this "close enough" that i should spend time resolving conflicts or scratch it?

**Comment by osheroff** [comment]
what's your main intent scott?  a simple monitoring port?

**Comment by smferguson** [comment]
i'm in a similar situation, maxwell deployed via marathon. it'd be nice to have a "process is up" in addition to a "here's my latest details" endpoint(s)

**Comment by osheroff** [comment]
I guess I'd encourage you to look into integrating http://metrics.dropwizard.io/3.1.0/ at least minimally, and maybe expose whatever REST interface that has?

**Comment by osheroff** [comment]
better to follow *some* kinda standard than to roll our own

**Comment by osheroff** [comment]
hey @smferguson if you haven't started anything around a web console or metrics or such I'm gonna take a first stab at it.  LMK

**Comment by smferguson** [comment]
@osheroff go for it. i haven't even read the docs yet.

**Comment by fala** [comment]
Hi @osheroff! Just wondering, are there any chances for the update in the near future? Looking forward to it :)

**Comment by smferguson** [comment]
@osheroff there's more interest for this here. where is it on your radar?

**Comment by osheroff** [comment]
@smferguson just there beneath the big torpedo heading my way.  :) haven't gotten time to look at it.  If you're interested in picking up any of it the first cut is here: https://github.com/zendesk/maxwell/compare/basic_metrics?expand=1.  Got some very basic metrics working, but didn't do any of the confiugration stuff or nothing.

**Comment by smferguson** [comment]
@osheroff ha! i have a window-of-opportunity here so i'll take a crack at it and see how far i get before the window closes. lmk if you survive the torpedo ;)

**Comment by timbertson** [comment]
I'm assuming this is superseded by #580 - feel free to reopen if I've missed something though :)

**Pull request closed without merging**
