### PR TITLE
Maxwell ha-mode

### PR DESCRIPTION
**Pull request by springloops**
Hi, I made Maxwell Active-Standby Mode using Apache Helix.

Apache Helix is library for zookeeper.

### CODE REVIEW

**Comment by osheroff** [comment]
Hi @springloops, 

Thanks for the contribution!

This PR is pretty invasive, so I won't merge it directly.  If you're willing to put more work in, the direction I could see for this:

1.  Merge https://github.com/zendesk/maxwell/pull/414
2. Get Maxwell packaged as a jar, deployed to maven central
3. Rework this code to be a wrapper-executable that consumes maxwell, and release it as a separate project (maxwell-helix?  maxwell-ha?).  

let me know.

**Comment by leeparayno** [comment]
@springloops Great work.  The code seems well done.  If anything, the change of Maxwell to an interface that is implementable seems like it may be the core issue.  The implementation does appear to be an optional setting so in that respect, the design decisions seem inline with this project.  

I must admit, this is one of the disadvantages of Maxwell in it's current form, without any ability to have HA makes such a key part of any data pipeline strategy an issue.

**Comment by springloops** [comment]
At first, I'm sorry that I don't clean PR.
I just first time PR into github, I had immature.

@leeparayno said, I changed maxwell class to maxwell interface.
And created MaxwellLauncher class.

MaxwellLauncher class have main method for running maxwellImpl or ActiveStandbyMaxwell class.
maxwellImpl class's role is just same maxwell class that just changed class name.

I wanted common structure for maxwell and ActiveStandbyMaxwell that to manage run(), stop().
Because that I main method extracted to MaxwellLauncher class, MaxwellLauncher must have manage maxwellImpl or ActiveStandbyMaxwell.

ActiveStandbyMaxwell is waiting distributed lock from zookeeper, if take lock (when Active is down.), just new MaxwellImpl.

ActiveStandbyMaxwell is just initialize helix code for zookeeper and wrapping the maxwellImpl.

please look follow class diagram.
class diagram



@osheroff 
I want to merge into maxwell, because I want to use the maxwell it will be upgrade in the future (opensource power).

So, I want your opinion for maxwell structure.
Do you want maintain maxwell class?
please let me know your opinions about structure.

P.S. I can't speak English very well, if you don't understand that my description, please let me know.
I will descript my code again.

**Comment by osheroff** [comment]
@springloops, 
thought about this some more.  I think I'm ok merging helix-functionality into master, but I'd like to get a slightly different structure:

image

So `Maxwell` stays the main class, with a `main`, and only the configuration that it needs to know about to run a replicator.  `MaxwellHelix` then sits as a wrapper on top of that `Maxwell` instance and does the zookeeper bits.  So you'd launch maxwell the same as normal:

```
bin/maxwell --host=XXX ...
```

and you'd have a separate launcher for helix functionality:

```
bin/maxwell_helix --zookeeper ... 
```

This does mean that `MaxwellHelix` would have to parse its own configuration and then pass the rest of the arguments to `Maxwell`.

Would that work?  Make sense?

**Comment by springloops** [comment]
Ok, I understand. 

I will change maxwell code and re-PR.

Thankyou for your opinion.

**Comment by osheroff** [comment]
cool.  please also rebase your work on top of the "refactor_main_maxwell" branch? That will be merging shortly and contains changes that are very similar to some of the stuff in this branch.

**Comment by springloops** [comment]
yep, I did `git rebase remotes/upstream/refactor_main_maxwell`.

It was good to use at new activestandbymaxwell.

Thank you.

**Comment by springloops** [comment]
Hi @osheroff 
We changed cord for maxwell ha mode about your opinions.
But I don't know that why failed.
What can i do for failed? Can you give to me TIP?
Thank you.

**Comment by osheroff** [comment]
@springloops, this looks like a problem with my `build/maven_fetcher`script, which I use to avoid the overhead of `mvn` (and because I'm crazy.)  I will look and see if I can't help with a fix.

**Comment by osheroff** [comment]
ok I fixed the build script to support exclusions.  if you merge the latest master hopefully your tests will pass (try `make test` locally).

Speaking of tests: will you be testing this in a production environment?  I will probably release it as an alpha-feature for awhile.  It would also be great to have unit/integration tests around this code, I'm not sure how painful that would be though.

**Comment by springloops** [comment]
We are testing on development environment but It will be used on production environment soon as.
about that unit/integration tests code, anywise we will be find method.
Can you restart build? Build  was success in my local system.

**Comment by osheroff** [comment]
hi @springloops,
how is this working in production?

**Comment by springloops** [comment]
Hi osheroff,

We are still being tested, but it's not ha-maxwell test.

We are changing from Legacy System to new System by new Architecture.

Production will take a little bit more because other system and migration.

**Comment by luyee** [comment]
how is it status  now?

**Pull request closed without merging**
