### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by samzx**

### CODE REVIEW

**Comment by samzx** [comment]
Hey @osheroff, I've added this project to circle ci. We can close this PR if you'd like to take over 🙂

**Comment by osheroff** [comment]
More than happy to let you run with it if you have the time and desire.  If not, let me know and I’ll take it.  Up to you!  Thanks for adding it.

**Comment by samzx** [comment]
Sorry for the late reply - I guess you're already on it, I'll let you continue 🙂 

Let us know if you need anything else!

**Comment by osheroff** [comment]
thanks @samzx.  Think you could figure out how to remove travis from the project?

**Comment by samzx** [comment]
yup sure, Ill take a crack at it

**Pull request merged**
