### PR TITLE
Adds ENCRYPTION to parsing for alter database statements

### PR DESCRIPTION
**Pull request by KelseyLMay**
We're getting the following error:

00:20:43,115 ERROR MysqlParserListener - (alter_database_definition ENCRYPTION = 'Y')
00:20:43,123 ERROR SchemaChange - Error parsing SQL: 'ALTER DATABASE XXX  ENCRYPTION = 'Y''
00:20:43,124 ERROR AbstractSchemaStore - Error on bin log position XXX
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: ENCRYPTION

This PR adds support for ENCRYPTION '='? string_literal in "ALTER DATABASE" statements similar to [the previous commit](https://github.com/zendesk/maxwell/commit/bf5113f6e5b2bdc558aad55c9422a5ae71dcd341) that made a similar adjustment for "CREATE TABLE" statements.

### CODE REVIEW

**Comment by osheroff** [comment]
thanks for the PR!  can you add a test in DDLParserTest please?

**Comment by KelseyLMay** [comment]
> thanks for the PR! can you add a test in DDLParserTest please?

Thanks for the reply @osheroff ! I added a scenario to the existing test for parsing logic:

"alter database d ENCRYPTION='Y'"

Do you prefer a separate test for this scenario or is that sufficient?

**Comment by osheroff** [comment]
nevermind me i'm trying to do two things at once and it's making me dumb.

**Comment by KelseyLMay** [comment]
No worries! Thanks so much for merging! This will really help my team!

**Pull request merged**
