### PR TITLE
fix bootstrapping with custom schema_database

### PR DESCRIPTION
**Pull request by lucianjon**
Fixes bootstrapping binlog events not being picked up when using a custom `schema_database`.
Addresses #471

### CODE REVIEW

**Comment by osheroff** [comment]
oh, is the missing piece of the puzzle here that you've also got an `include_database=` (or other `include`) filter configured?  that.... would make sense.

**Comment by osheroff** [comment]
thanks for the patch!  tell ya what though, how about we move the hard-coded whitelist outside of the filter?  IMO it was in the wrong place anyway; IMO the place for the hard-coded check should be around line 280 in MaxwellReplicator.java, where we check the filter.

**Comment by lucianjon** [comment]
Yep, we're using an `include_database` as well as `include_tables`. 

Yeah that makes sense to me, passing the `schema_database` into the filter class didn't feel too great. So you're thinking something like this?

```
if ( event.matchesFilter() || bootstrapRow ) {
 addToBuffer
}
```

**Comment by osheroff** [comment]
yup, like that.  If you wanted to get fancy you could name it `isSystemWhitelisted` or something.

**Comment by lucianjon** [comment]
Cool, that looks to be working. Just figuring out a way to add a test for this.

**Comment by osheroff** [comment]
this looks good to me, were you planning on trying a test here?  you could maybe try a a bootstrap-integration test with an include-dbs filter or something.  i dunno.

**Comment by lucianjon** [comment]
Yep, I'm working on a test in BootstrapIntegrationTest. I just have to add the ability to pass a filter down through the JSON helper functions. I also wanted to run it against a non-default maxwell schema but that looks a little tricky as it's hard coded inside `getRowsWithReplicator`

**Comment by lucianjon** [comment]
@osheroff Got the test, does the PR look good to you?

**Comment by osheroff** [comment]
looks good.  thanks for the work! 👍

**Pull request merged**
