### PR TITLE
Allow Publishers to produce messages by thread ID

### PR DESCRIPTION
**Pull request by jl-gogovapps**
Based on discussion #1525 
```
21:11:40,738 DEBUG KinesisCallback - ->  key:820361, shard id:shardId-000000000000, sequence number:49608083649042269680942954152460432258721642278002098178
21:11:40,738 DEBUG KinesisCallback -    {"database":"xxx","table":"xxx","type":"insert","ts":1593465100,"xid":26209465,"commit":true,"position":"mysql-bin-changelog.146334:257588","server_id":382330091,"thread_id":820361,"schema_id":12,"primary_key":[135449],"primary_key_columns":["id"],"data":{...}}
```

The update here is that the `key:820361` corresponds with the thread id

### CODE REVIEW

**Comment by osheroff** [comment]
looks good thx!  sorry to bug you but can you undo the changes that bump the version?  I have a scripts that do that upon release and this will mess them up

**Comment by jl-gogovapps** [comment]
Ah, no problem, I should be able to get to this today.  Thanks!  
I've been running this in our staging environment since yesterday morning, haven't **observed** any issues so far

**Comment by jl-gogovapps** [comment]
Just wanted to share this bit of code too, if someone were searching the depths of the internet like I was :D 

```
  class Cdc
    def initialize app
      @app = app
    end

    def generate_marker(env)
      request = Rack::Request.new(env)
      actor_id = request.env[:token]&.dig('data','user','id')
      context = {
        actor_id: actor_id,
        ip_address: request.forwarded_for || request.ip
      }
      ActiveRecord::Base.connection.execute(
        <<SQL
INSERT INTO cdc_thread_requests (thread_id, context) VALUES (CONNECTION_ID(), '#{JSON.generate(context)}')
SQL
      )
    end

    def should_generate_marker?(env)
      return false if env['REQUEST_METHOD'].downcase.to_sym == :options
      return false if ENV['RACK_ENV'] == 'test'
      true
    end

    def call env
      generate_marker(env) if should_generate_marker?(env)
      response = @app.call(env)
      generate_marker(env) if should_generate_marker?(env)
      response
    end
  end
```

In a sinatra app, for example:
```
use Cdc
```
after verifying and unpacking a JWT token into `env[:token]`

**Comment by osheroff** [comment]
thx for paying it forward.

**Pull request merged**
