### PR TITLE
build under 5.7

### PR DESCRIPTION
**Pull request by osheroff**

### CODE REVIEW

**Comment by osheroff** [comment]
@zendesk/rules this starts us testing under mysql 5.7

**Comment by dadah89** [comment]
I was checking the upgrade/release notes, some tables moved from information_schema to performance_schema, but not the ones maxwell cares about. There is some change to `show variables`, but afaict it should work the same.
Any fixes needed, or is this ready to go?

**Comment by osheroff** [comment]
this is fine to merge (just get the tests going), I'm going to say that 5.7 support is alpha-quality at best in the next release.

**Comment by smferguson** [comment]
@osheroff fyi, i just fetched upstream, got this code and it doesn't build :/
```[ERROR] /Users/sferguson/dev/maxwell/src/main/java/com/zendesk/maxwell/replication/BinlogConnectorReplicator.java:[56,73] cannot find symbol
  symbol:   variable CompatibilityMode
  location: class com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer
[ERROR] /Users/sferguson/dev/maxwell/src/main/java/com/zendesk/maxwell/replication/BinlogConnectorReplicator.java:[57,42] cannot find symbol```

**Pull request merged**
