### PR TITLE
improve enum values extraction

### PR DESCRIPTION
**Pull request by sinceat**
Currently enum values containing commas will lead to a StringIndexOutOfBoundsException

### CODE REVIEW

**Comment by osheroff** [comment]
can you write a test exposing the issue?

**Comment by sinceat** [comment]
I've added a test, although I'm not sure why the build didn't kick in.

**Comment by osheroff** [comment]
travis and pretty much the rest of the known internet have been having problems bcs of aws issues today

**Comment by osheroff** [comment]
fails with `make test`.  you probably want to change your test to do `CREATE TABLE IF NOT EXISTS`

**Comment by osheroff** [comment]
hmmm, if we're gonna fix this let's fix it for real.  How about simply serializing them into a JSON array in schema version 4?  that should handle problems with pathological columns that include a `'` character too. 

@vanchi-zendesk I owe you a coffee on this one.

**Comment by sinceat** [comment]
json be it then.

**Pull request merged**
