### PR TITLE
fix parsing config file

### PR DESCRIPTION
**Pull request by lileeyao**
@osheroff 
fix https://github.com/zendesk/maxwell/pull/314

### CODE REVIEW

**Comment by lileeyao** [comment]
should replication config have `jdbc_options` too?

**Comment by osheroff** [comment]
plz undo the whitespace changes.  makes it very hard to read what you've actually changed.  and yeah, the replication config should support jdbc_options (and it should default to the other jdbc_options, same as how the rest of it does)

**Comment by lileeyao** [comment]
@osheroff

**Comment by osheroff** [comment]
cool.  now the naming of things: 

`parseJdbcOptions` -> `parseJDBCOptions`
and 
the variable `jdbc_options` -> `jdbcOptions` (but not the config option)

**Comment by lileeyao** [comment]
ping

**Comment by osheroff** [comment]
👍

**Pull request merged**
