### PR TITLE
Fix for #134 - duplicate tables being created.

### PR DESCRIPTION
**Pull request by davidsheldon**
If the CREATE ... IF NOT EXISTS ran on the upstream server, then we wont already know it. If it failed, or didn't create the table, then leave the schema alone.

### CODE REVIEW

**Comment by osheroff** [comment]
nice catch.  a couple of things:

- can you write a test that exposes this issue?  `DDLIntegrationTest` looks like about the right place to put an issue like this.
- there's an `ifNotExists` pattern here: https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/schema/ddl/DatabaseCreate.java#L19 which is a little bit safer (crash if asked to create an existing table, unless if-not-exists is true), can you add that to your patch?

thanks!
-ben

**Comment by davidsheldon** [comment]
In DDLIntegration test I couldn't check for the exact case (table defined the same multiple times, as the schema diff functions don't seem to mind), but if we try to redefine the table to a different schema it does detect that both of them are in the schema and different.

**Comment by davidsheldon** [comment]
Whilst this solves the bug of several tables being created in each schema, it still allocates a new schemaId, and writes a whole new schema to the database whenever we process one of these messages.

Would it be sensible to somehow check if the new schema is different, rather than just count the potential changes in https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellReplicator.java#L282

**Comment by osheroff** [comment]
:+1: on the changes, looks like the schema-diff procedure needs to check the number of tables in each database, eh?  

Discussed the schema check in the other PR; I think it's good enough to say that if we get back the same object we started with, it's a no-op and we don't need to re-save the schema.

**Pull request merged**
