### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by osheroff**
mostly stuff around getting a release together, but also a bug fix or two.

@vanchi-zendesk

### CODE REVIEW

**Comment by osheroff** [comment]
ping

**Comment by vanchi-zendesk** [comment]
The test fail is fine?
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

at java.util.ArrayList.rangeCheck(ArrayList.java:635)
```

**Comment by vanchi-zendesk** [comment]
changes look ok to me. But I am still concerned by the strange test fail.

+1

**Comment by osheroff** [comment]
yeah I think it's a race condition ultimately; if the binlog parser thread hasn't gotten going by the time `.getEvent()` is called it will just return early.  I will look into something more robust later.

**Pull request merged**
