### PR TITLE
feat: add arm64 support for docker images

### PR DESCRIPTION
**Pull request by VictorVasconcelos**

### CODE REVIEW

**Comment by osheroff** [comment]
looks good!  let's see if it works...

**Comment by osheroff** [comment]
Hey @VictorVasconcelos looks like I'm running afoul of zendesk's policy of not allowing foreign actions into their repos.  maybe we can just setup `qemu` and `buildx` with shell scripts?

**Comment by VictorVasconcelos** [comment]
Ok @osheroff, I will send another PR with custom actions

**Comment by VictorVasconcelos** [comment]
Sent PR #1777

**Pull request merged**
