### PR TITLE
Adding encryption capability

### PR DESCRIPTION
**Pull request by Bradyta**
Optionally encrypts the data field using input parameters.

### CODE REVIEW

**Comment by Bradyta** [comment]
Not sure why the tests fail in Travis but not locally..

**Comment by Bradyta** [comment]
So for some reason, the encrypted string is changing once it gets onto travis, but not locally. It's going from 

1ub4DX5FGXqLnDWK6nhrZAY6sbwNvItFnTPzpByMNX4BuIRIgNq7rybo+hztXCdD
to
WXGOoMWluiiRiH4+T4ugzWQn1VPE4edWOXBTFDfFK9D32QEqdILuWSib9xVzHyTH  
  
Please advise.

**Comment by osheroff** [comment]
can't tell you for sure, but it's likely that your method of re-parsing the `data` value after it's already generated is triggering untestable behavior -- there's no guarantee that the ordering of data will stay the same. 

Suggest that you move your encryption to be in the neighborhood of https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/row/RowMap.java#L260 -- so instead of generating the whole JSON blob, when you go to write the `data` part of the json you write to a separate byte-array that you then encrypt, inline.  This means you won't have to re-parse the JSON, and will also mean that the key order will stay stable.

Out of curiousity, is your business requirement that the entire payload be encrypted, or is it just some fields?  Would it be just as good to encrypt the entire payload (not just the data section), or to selectively encrypt fields inside the data payload?  Just strikes me as a bit odd that we're tunneling the hash inside the `data` payload.

**Comment by Bradyta** [comment]
I agree that it should be moved inline, I'm working on that now and hopefully that solves the issue, although we've yet to have issues with that ever on our platform.  
  
In terms of necessity we would only only *need* certain fields encrypted, but they're numerous and having the databases and tables unencrypted (we add in the primary key values into a sorted comma delimited string too) allows us to perform some basic ETL processes before getting into the gnitty gritty. Having the fields encrypted individually would cause performance issues because then we're not doing 1 decryption we're determining what needs it and then doing several.

**Comment by osheroff** [comment]
would the unencrypted info in the kafka key be enough to do your basic filtering?   It should have (database,table,primary-key-values). Just seems like that way we could encrypt the whole payload and push the message as binary data rather than having to do the weird encrypt-inside-json thing

**Comment by Bradyta** [comment]
That's an interesting point, we just don't use the kafka component ourselves, we use the stdout producers to write to file. I moved things around but am still working on figuring out why the encrypted string is different on travis than it is locally.

**Comment by osheroff** [comment]
hmmm, interesting.  what if the stdout producer could option prefix the message with what would be the kafka key?  In general I see a lot of format/producer PRs that are specific to single business use case, and while I love features, I'm generally trying to make them somewhat general.

I've also thought about trying to open up formatting a message with a little DSL or something but it seems overblown.

**Comment by Bradyta** [comment]
I'm having a hard time thinking this one through pros-cons  
If you encrypt the whole thing and prefix it with the kafka key, maybe someone wanted the primary key columns encrypted and you're redundant.  
If you encrypt the whole thing and don't prefix it, maybe someone wants to be able to do certain ETL processes without decrypting.  
If you encrypt the whole thing without kafka and then have to prefix you're being redundant.  
If you encrypt the data field without kafka like I have it, then your data decryption step is messy and you fail the travis tests. :)   
  
I guess in regards to this PR what's important is, what's your preferred solution?

**Comment by osheroff** [comment]
Thanks for thinking of my preferences :)  I think for a first pass my preferred solution is this:

1.  Encrypt the entire payload.  Add a flag to toggle base-64 encoding.
2.  Add a flag to the stdout producer `--stdout_key_prefix=SEPARATOR`, which enables prefixing the message with the kafka key (unencrypted).  Should be able to use `\n` and `\t` here, as well as `:` or whatever. 

That should I think satisfy your use case ok, as well as being generalized enough for most use cases.   The only thing this doesn't support is encrypting the kafka keys, but I think that's ok for now, if someone comes along and *must* have that they can add it.

**Comment by smferguson** [comment]
@Bradyta looks like this might be getting stale. is it still on your radar?

**Comment by BradyPT** [comment]
@osheroff @smferguson  
  
Got some time to revisit this today while updating to 1.8.1, I think the best option would be to only encrypt the data attribute right now as a default if use_encryption is set to true, and then add an additional flag to encrypt the other attributes if desired. I think if you were to encrypt the whole payload and have the option to prefix it you're adding too much redundancy and mess unless you then go in and strip out the non-data attributes.

**Comment by Bradyta** [comment]
@osheroff @smferguson

Got some time to revisit this today while updating to 1.8.1, I think the best option would be to only encrypt the data attribute right now as a default if use_encryption is set to true, and then add an additional flag to encrypt the other attributes if desired. I think if you were to encrypt the whole payload and have the option to prefix it you're adding too much redundancy and mess unless you then go in and strip out the non-data attributes.

**Pull request closed without merging**
