### PR TITLE
default to binlog-connector mode

### PR DESCRIPTION
**Pull request by osheroff**
it's time enough that we just turned on this option by default.

### CODE REVIEW

**Comment by liulikun** [comment]
Looks good! We can also cleanup `.travis.yml` a bit I think.

**Comment by osheroff** [comment]
@liulikun good point, done

**Comment by liulikun** [comment]
Thanks! 🎉 👍

**Comment by adhiemsumitro** [comment]
How to know if this has been implemented on the latest binary ? I just realize that  the repository doesn't include a compiled binary (newbie here, 3 weeks usage)

**Comment by liulikun** [comment]
You can check the releases: https://github.com/zendesk/maxwell/releases, is that what you are asking?

**Pull request merged**
