### PR TITLE
transition to "onetimeserver" utility 

### PR DESCRIPTION
**Pull request by osheroff**
I've been working on a golang replacement for mysql_isolated_server here: https://github.com/osheroff/onetimeserver.  

it bootstraps all of its own binaries, so we win being able to test maxwell under multiple versions of mysql.  

@zendesk/rules

### CODE REVIEW

**Comment by osheroff** [comment]
should make great improvements on https://github.com/zendesk/maxwell/issues/106 @magaton

**Comment by vanchi-zendesk** [comment]
:+1: tested locally on macos. @dadah89 want to give it a try on your Linux box?

**Comment by dadah89** [comment]
sure, taking a look

**Comment by dadah89** [comment]
works just fine! also seems to shutdown properly on my VM =) :+1:

**Pull request merged**
